bbb

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,8 +9,7 @@ apt-get update -qq
 apt-get install -y -qq \
     build-essential \
     zlib1g-dev \
-    libpcre3 \
-    libpcre3-dev \
+    libpcre2-dev \  # Changed to PCRE2
     g++ \
     curl \
     pkg-config \
@@ -18,13 +17,8 @@ apt-get install -y -qq \
     cpp \
     make
 
-# Verify compiler installations
-echo "-----> Verifying compiler installations"
-gcc --version
-g++ --version
-
 echo "-----> Downloading and installing OpenSSL"
-OPENSSL_DIR="$HOME/openssl"  # Using $HOME instead of /app
+OPENSSL_DIR="$HOME/openssl"
 rm -rf $OPENSSL_DIR
 mkdir -p $OPENSSL_DIR
 cd $HOME
@@ -37,36 +31,10 @@ make clean
 make -j$(nproc) || { echo "OpenSSL make failed"; exit 1; }
 make DESTDIR=$HOME install_sw || { echo "OpenSSL install failed"; exit 1; }
 
-echo "-----> Downloading and installing PCRE library"
-PCRE_DIR="$HOME/pcre"
-mkdir -p $PCRE_DIR
-cd $HOME
-curl -fSL https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download -L -o pcre-8.45.tar.gz || { echo "PCRE download failed"; exit 1; }
-tar -xzf pcre-8.45.tar.gz
-cd pcre-8.45
-
-# Set compiler flags explicitly
-export CC="gcc"
-export CXX="g++"
-export CFLAGS="-O2 -fPIC"
-export CXXFLAGS="-O2 -fPIC"
-export LDFLAGS="-L$HOME/pcre/lib"
-
-# Run configure with explicit compiler settings
-./configure \
-    --prefix=$PCRE_DIR \
-    --enable-utf8 \
-    --enable-unicode-properties \
-    --with-pic \
-    CC="gcc" \
-    CXX="g++" \
-    || { echo "PCRE configure failed"; exit 1; }
-
-
 echo "-----> Downloading and installing zlib"
-ZLIB_DIR="$BUILD_DIR/zlib"
+ZLIB_DIR="$HOME/zlib"  # Changed to use $HOME
 mkdir -p $ZLIB_DIR
-cd $BUILD_DIR
+cd $HOME
 curl -fSL http://zlib.net/zlib-1.2.13.tar.gz -o zlib-1.2.13.tar.gz || { echo "zlib download failed"; exit 1; }
 tar -xzf zlib-1.2.13.tar.gz
 cd zlib-1.2.13
@@ -75,24 +43,23 @@ make -j$(nproc) || { echo "zlib make failed"; exit 1; }
 make install || { echo "zlib install failed"; exit 1; }
 
 echo "-----> Installing nginx"
-NGINX_DIR="$BUILD_DIR/nginx"
+NGINX_DIR="$HOME/nginx"  # Changed to use $HOME
 mkdir -p $NGINX_DIR
-cd $BUILD_DIR
+cd $HOME
 curl -fSL https://nginx.org/download/nginx-1.25.3.tar.gz -o nginx-1.25.3.tar.gz || { echo "Nginx download failed"; exit 1; }
 tar -xzf nginx-1.25.3.tar.gz
 cd nginx-1.25.3
 ./configure \
     --prefix=$NGINX_DIR \
     --with-http_ssl_module \
-    --with-pcre=$BUILD_DIR/pcre-8.45 \
-    --with-openssl=$BUILD_DIR/openssl-3.0.8 \
-    --with-zlib=$BUILD_DIR/zlib-1.2.13 || { echo "Nginx configure failed"; exit 1; }
+    --with-pcre \  # Changed to use system PCRE2
+    --with-openssl=$HOME/openssl-3.0.8 \
+    --with-zlib=$HOME/zlib-1.2.13 || { echo "Nginx configure failed"; exit 1; }
 make -j$(nproc) || { echo "Nginx make failed"; exit 1; }
 make install || { echo "Nginx install failed"; exit 1; }
 
 # Cleanup source files
-cd $BUILD_DIR
+cd $HOME
 rm -rf openssl-3.0.8.tar.gz openssl-3.0.8
-rm -rf pcre-8.45.tar.gz pcre-8.45
 rm -rf zlib-1.2.13.tar.gz zlib-1.2.13
 rm -rf nginx-1.25.3.tar.gz nginx-1.25.3
