vjhvjvj

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -35,7 +35,18 @@ cd $HOME
 curl -fSL https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download -L -o pcre-8.45.tar.gz || { echo "PCRE download failed"; exit 1; }
 tar -xzf pcre-8.45.tar.gz
 cd pcre-8.45
-./configure --prefix=$PCRE_DIR || { echo "PCRE configure failed"; exit 1; }
+
+# Set compiler environment variables
+export CC=gcc
+export CXX=g++
+export CFLAGS="-O2"
+export CXXFLAGS="-O2"
+
+./configure \
+    --prefix=$PCRE_DIR \
+    --enable-utf8 \
+    --enable-unicode-properties \
+    || { echo "PCRE configure failed"; exit 1; }
 make -j$(nproc) || { echo "PCRE make failed"; exit 1; }
 make install || { echo "PCRE install failed"; exit 1; }
 
